name: Actionlint

on:
  pull_request:
    paths:
      - '.github/actions/**/*'
      - '.github/workflows/**/*'

jobs:
  actionlint:
    uses: kieranbrown/github-actions/.github/workflows/actionlint.yaml@v1
    permissions:
      contents: write
