name: metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  metrics:
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    permissions: {}
    steps:
      - uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6 # v3.34
        with:
          template: terminal
          token: ${{ secrets.METRICS_TOKEN }}
