name: metrics

on:
  workflow_dispatch:
  schedule: ## 3am every day
    - cron: "0 3 * * *"
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  metrics:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6 # v3.34
        with:
          template: terminal
          token: ${{ secrets.METRICS_TOKEN }}
